export const ACTION_TYPES = {
    PUSH_STACK: 'PUSH_STACK',
    POP_STACK: 'POP_STACK',
    ADD_WEB_API: 'ADD_WEB_API',
    REMOVE_WEB_API: 'REMOVE_WEB_API',
    ENQUEUE_CALLBACK: 'ENQUEUE_CALLBACK',
    DEQUEUE_CALLBACK: 'DEQUEUE_CALLBACK',
    ENQUEUE_MICROTASK: 'ENQUEUE_MICROTASK',
    DEQUEUE_MICROTASK: 'DEQUEUE_MICROTASK',
    CONSOLE_LOG: 'CONSOLE_LOG',
};
